/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class spade_reporter_FusionFUSE */

#ifndef _Included_spade_reporter_FusionFUSE
#define _Included_spade_reporter_FusionFUSE
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     spade_reporter_FusionFUSE
 * Method:    launchFUSEServer
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_spade_reporter_FusionFUSE_launchFUSEServer
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
